[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "fotoin"
version = "0.1.0"
requires-python = ">=3.11"
dynamic = ["dependencies"]

[project.scripts]
fotoin = "fotoin.cli:main"

[tool.setuptools]
packages = ["fotoin"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
